// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/ej_tp2_daniel.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class ej_tp2_daniel {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object Q=$fix($opUnionY($opIntvlY(0,23),GCollections.asSet("err")));
      $line=6;
      Object \u03A3=$fix($opUnionY($opUnionY($opUnionY($opIntvlY('a','z'),GCollections.asSet(' ')),GCollections.asSet('=','>','<')),GCollections.asSet('0','1','2','3','4','5','6','7','8','9')));
      $line=7;
      Object q=$fix(0);
      $line=8;
      Object F=$fix(GCollections.asSet(9));
      $line=12;
      GDeterministicAutomaton A=$cast(GDeterministicAutomaton.class,$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,q,F,new GMethod(ej_tp2_daniel.class,"\u03B4")})));
      $line=13;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ej_tp2_daniel.class,"main",$line);
    }
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=18;
      if ($opEqualY(q,"err")) {
        $line=19;
        $result="err";
        if (true) break $try;
      }
      $line=21;
      if (($opEqualY(q,0)&&$opEqualY(\u03C3,'b'))) {
        $line=22;
        $result=1;
        if (true) break $try;
      }
      else {
        $line=23;
        if (($opEqualY(q,1)&&$opEqualY(\u03C3,'e'))) {
          $line=24;
          $result=2;
          if (true) break $try;
        }
        else {
          $line=25;
          if (($opEqualY(q,2)&&$opEqualY(\u03C3,'g'))) {
            $line=26;
            $result=3;
            if (true) break $try;
          }
          else {
            $line=27;
            if (($opEqualY(q,3)&&$opEqualY(\u03C3,'i'))) {
              $line=28;
              $result=4;
              if (true) break $try;
            }
            else {
              $line=29;
              if (($opEqualY(q,4)&&$opEqualY(\u03C3,'n'))) {
                $line=30;
                $result=5;
                if (true) break $try;
              }
              else {
                $line=31;
                if (($opEqualY(q,5)&&$opEqualY(\u03C3,' '))) {
                  $line=32;
                  $result=6;
                  if (true) break $try;
                }
                else {
                  $line=35;
                  if (($opEqualY(q,6)&&$opEqualY(\u03C3,'i'))) {
                    $line=36;
                    $result=10;
                    if (true) break $try;
                  }
                  else {
                    $line=37;
                    if (($opEqualY(q,10)&&$opEqualY(\u03C3,'f'))) {
                      $line=38;
                      $result=11;
                      if (true) break $try;
                    }
                    else {
                      $line=39;
                      if (($opEqualY(q,11)&&$opEqualY(\u03C3,' '))) {
                        $line=40;
                        $result=12;
                        if (true) break $try;
                      }
                      else {
                        $line=41;
                        if (($opEqualY(q,12)&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
                          $line=42;
                          $result=13;
                          if (true) break $try;
                        }
                        else {
                          $line=44;
                          if (($opEqualY(q,13)&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
                            $line=45;
                            $result=13;
                            if (true) break $try;
                          }
                          else {
                            $line=47;
                            if (($opEqualY(q,13)&&$opEqualY(\u03C3,' '))) {
                              $line=48;
                              $result=14;
                              if (true) break $try;
                            }
                            else {
                              $line=49;
                              if (($opEqualY(q,14)&&$opMembrY(\u03C3,GCollections.asSet('=','>','<')))) {
                                $line=50;
                                $result=15;
                                if (true) break $try;
                              }
                              else {
                                $line=51;
                                if (($opEqualY(q,15)&&$opEqualY(\u03C3,' '))) {
                                  $line=52;
                                  $result=16;
                                  if (true) break $try;
                                }
                                else {
                                  $line=54;
                                  if (($opEqualY(q,16)&&$opMembrY(\u03C3,GCollections.asSet('0','1','2','3','4','5','6','7','8','9')))) {
                                    $line=55;
                                    $result=17;
                                    if (true) break $try;
                                  }
                                  else {
                                    $line=56;
                                    if (($opEqualY(q,17)&&$opMembrY(\u03C3,GCollections.asSet('0','1','2','3','4','5','6','7','8','9')))) {
                                      $line=57;
                                      $result=17;
                                      if (true) break $try;
                                    }
                                    else {
                                      $line=58;
                                      if (($opEqualY(q,17)&&$opEqualY(\u03C3,' '))) {
                                        $line=59;
                                        $result=18;
                                        if (true) break $try;
                                      }
                                      else {
                                        $line=60;
                                        if (($opEqualY(q,18)&&$opEqualY(\u03C3,'t'))) {
                                          $line=61;
                                          $result=19;
                                          if (true) break $try;
                                        }
                                        else {
                                          $line=62;
                                          if (($opEqualY(q,19)&&$opEqualY(\u03C3,'h'))) {
                                            $line=63;
                                            $result=20;
                                            if (true) break $try;
                                          }
                                          else {
                                            $line=64;
                                            if (($opEqualY(q,20)&&$opEqualY(\u03C3,'e'))) {
                                              $line=65;
                                              $result=21;
                                              if (true) break $try;
                                            }
                                            else {
                                              $line=66;
                                              if (($opEqualY(q,21)&&$opEqualY(\u03C3,'n'))) {
                                                $line=67;
                                                $result=22;
                                                if (true) break $try;
                                              }
                                              else {
                                                $line=68;
                                                if (($opEqualY(q,22)&&$opEqualY(\u03C3,' '))) {
                                                  $line=69;
                                                  $result=23;
                                                  if (true) break $try;
                                                }
                                                else {
                                                  $line=72;
                                                  if ($opEqualY(\u03C3,'e')) {
                                                    $line=73;
                                                    $result=7;
                                                    if (true) break $try;
                                                  }
                                                  else {
                                                    $line=74;
                                                    if (($opEqualY(q,7)&&$opEqualY(\u03C3,'n'))) {
                                                      $line=75;
                                                      $result=8;
                                                      if (true) break $try;
                                                    }
                                                    else {
                                                      $line=76;
                                                      if (($opEqualY(q,8)&&$opEqualY(\u03C3,'d'))) {
                                                        $line=77;
                                                        $result=9;
                                                        if (true) break $try;
                                                      }
                                                      else {
                                                        $line=80;
                                                        $result="err";
                                                        if (true) break $try;
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=85;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ej_tp2_daniel.class,"\u03B4",$line);
    }
    return $result;
  }
}
